/**
 * Catalog map for the SFX library — families, counts, and what each is for.
 *
 * AUTO-GENERATED by scripts/sfx_rag/build_catalog_manifest.py — do not hand-edit.
 */

export type SfxMode = "hit" | "build" | "bed" | "sting" | "meme";

export interface SfxFamily {
  category: string;
  count: number;
  mode: SfxMode;
  use: string;
  examples: string[];
}

export interface SfxCatalogManifest {
  totalClips: number;
  families: SfxFamily[];
}

export const CATALOG_MANIFEST: SfxCatalogManifest = {
  totalClips: 180,
  families: [
    {
      category: "impact",
      count: 29,
      mode: "hit",
      use: "Slams, booms, sub-drops — punctuate a hit or number landing on the impact frame.",
      examples: ["Sub Drop", "Slam 1", "Slam 2"],
    },
    {
      category: "foley",
      count: 27,
      mode: "hit",
      use: "Real-world textures — footsteps, taps, rips, handling; realism and walk cycles.",
      examples: ["Single Footstep", "Heavy Footstep", "Tape Rip 1"],
    },
    {
      category: "whoosh",
      count: 22,
      mode: "hit",
      use: "Transitions and scene changes — fire on the cut.",
      examples: ["Whoosh", "Whoosh effect", "Whoosh bamboo"],
    },
    {
      category: "meme",
      count: 14,
      mode: "meme",
      use: "Cultural punchlines — vine boom, record scratch, air horn, sad trombone; sparingly, on a comedic turn.",
      examples: ["Vine Boom", "Heavy Record Scratch", "Air Horn"],
    },
    {
      category: "stinger",
      count: 13,
      mode: "sting",
      use: "Logo reveals, brand intros, suspense stings — on a reveal or lock.",
      examples: ["Suspense Sting 1", "Calm Elegant Logo", "Epic Logo Reveal"],
    },
    {
      category: "bell",
      count: 9,
      mode: "hit",
      use: "Bells, chimes, doorbells, alarms — alerts and gentle accents.",
      examples: ["Doorbell", "Chime", "Old Phone Ring"],
    },
    {
      category: "ui",
      count: 9,
      mode: "hit",
      use: "Clicks, taps, sparkles, beeps — on an interaction.",
      examples: ["Generic Click", "Sparkle", "Censor Beep"],
    },
    {
      category: "human",
      count: 6,
      mode: "bed",
      use: "Crowd cheer, applause, heartbeat — reactions and tension (cheers/applause can run as beds).",
      examples: ["General Crowd Cheer", "Polite Audience Applause", "Slow Human Heartbeat"],
    },
    {
      category: "ambience",
      count: 6,
      mode: "bed",
      use: "Drones, tension beds, sci-fi hum, stadium roar — run UNDER a scene for mood; not on a beat.",
      examples: ["Eerie Deep Tension", "Slow Resonant Tension", "Sci Fi Hum"],
    },
    {
      category: "downlifter",
      count: 5,
      mode: "build",
      use: "Descending sweeps and sub-drops — out of a transition or to deflate energy.",
      examples: ["Downlifter deep", "Zoom out pull effect", "Sfx medium subdown sound effect"],
    },
    {
      category: "riser",
      count: 5,
      mode: "build",
      use: "Ascending builds into a climax — place so the peak lands on the beat.",
      examples: ["Riser", "Heavy Metallic Riser", "Soft Dreamy Riser"],
    },
    {
      category: "notification",
      count: 5,
      mode: "hit",
      use: "Pings, alerts, 'correct' tones — confirmations.",
      examples: ["Ping", "Correct", "SMS Alert"],
    },
    {
      category: "glitch",
      count: 4,
      mode: "hit",
      use: "Digital errors and stutters — tech and hard-cut accents.",
      examples: ["Digital Error 1", "Digital Error 2", "Glitch Effect 1"],
    },
    {
      category: "nature",
      count: 4,
      mode: "bed",
      use: "Wind, rain, thunder — outdoor ambience or a weather hit.",
      examples: ["Wind", "Rain", "Sharp Thunder Clap"],
    },
    {
      category: "vehicle",
      count: 4,
      mode: "hit",
      use: "Sirens, engines, crashes — scene and action sounds.",
      examples: ["Police Siren", "Car engine", "Car crash sound effect"],
    },
    {
      category: "weapon",
      count: 4,
      mode: "hit",
      use: "Sword slices and swings, shots — action accents.",
      examples: ["Sword slice", "Sword slash and swing", "Pistol Shot"],
    },
    {
      category: "money",
      count: 3,
      mode: "hit",
      use: "Coin jingles, cash-register ka-ching — reward or purchase.",
      examples: ["Multiple Coins Jingle", "Cash Register 'Kaching'", "Whoosh and Cash Register"],
    },
    {
      category: "animal",
      count: 3,
      mode: "hit",
      use: "Crickets, duck quack — nature beds or comedic accents.",
      examples: ["Cricket Chirp", "Duck Quack"],
    },
    {
      category: "success",
      count: 2,
      mode: "hit",
      use: "Coin-collect chime, achievement — completion and reward.",
      examples: ["Coin Collect Chime", "Achievement"],
    },
    {
      category: "pop",
      count: 2,
      mode: "hit",
      use: "Pops — element pop-ins.",
      examples: ["Heart Pop", "Standard Pop"],
    },
    {
      category: "water",
      count: 2,
      mode: "hit",
      use: "Splash and drop — water hits.",
      examples: ["Water Splash", "Water Drop"],
    },
    {
      category: "tech",
      count: 2,
      mode: "sting",
      use: "Sci-fi logo reveals — futuristic intros.",
      examples: ["Sci fi intro logo reveal"],
    },
  ],
};
